name: Build Chromium 32-bit (r25c)

on: [push, pull_request]

jobs:
  build_32:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup NDK r25c (32-bit)
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Compile 32-bit
        run: |
          mkdir build_32 && cd build_32
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=armeabi-v7a \
            -DANDROID_PLATFORM=android-24 \
            -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          # Файл остается с оригинальным именем html_chromium.so

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lib_armeabi-v7a
          path: build_32/html_chromium.so
